#!/usr/bin/env bash
# Reason: OB and CK build inside their own containers with bundled toolchains
# (OB ships clang-17 in deps/3rd/; CK needs LLVM 20). Their compile_commands.json
# uses container-internal paths the host clangd cannot resolve, and rebuilding
# both trees on the host is impractical. This script drops a static .clangd
# into each submodule so clangd can jump-to-def and find-references within the
# tree without a real build.
#
# Local: idempotent. The submodule .gitmodules entries use `ignore = untracked`
# so these files do not appear in `git status`. Re-run after a fresh submodule
# checkout.
set -euo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel)}"
OB_DIR="${ROOT}/repos/source/oceanbase-v4.5.0_CE"
CK_DIR="${ROOT}/repos/source/ClickHouse-v26.3.10.62-lts"

write_ob_clangd() {
  cat >"${OB_DIR}/.clangd" <<EOF
# Auto-generated by scripts/lsp/install-clangd.sh. Edit the script, not this file.
#
# Static clangd config for read-only navigation of the OceanBase source tree.
# OB builds in its own container with bundled clang-17 under deps/3rd/; with
# deps/3rd/ absent on disk we cannot reconfigure, so these -I roots let clangd
# resolve OB-internal includes (share/, sql/, observer/, lib/, easy/, ...)
# without a build. The submodule's .gitmodules entry has ignore = untracked,
# so this file does not appear in git status. Reinstall via
# \`just repos-lsp-static\` after a fresh submodule checkout.
CompileFlags:
  Add:
    - -std=gnu++17
    - -D__x86_64__
    - -DOS_LINUX
    - -I${OB_DIR}/src
    - -I${OB_DIR}/deps/oblib/src
    - -I${OB_DIR}/deps/oblib/src/lib
    - -I${OB_DIR}/deps/easy/src
Diagnostics:
  Suppress: '*'
EOF
  echo "wrote ${OB_DIR}/.clangd"
}

write_ck_clangd() {
  cat >"${CK_DIR}/.clangd" <<EOF
# Auto-generated by scripts/lsp/install-clangd.sh. Edit the script, not this file.
#
# Static clangd config for read-only navigation of the ClickHouse source tree.
# CK needs LLVM 20 + a full thirdparty build to produce a real compile_commands;
# this static config gives jump-to-def and find-references on the host without
# a build. It replaces upstream's .clangd (which only configured a couple of
# ClangTidy checks) — the tradeoff is losing those lints. The submodule's
# .gitmodules entry has ignore = untracked, so this file does not appear in
# git status. Reinstall via \`just repos-lsp-static\` after a fresh submodule
# checkout.
CompileFlags:
  Add:
    - -std=c++23
    - -D__x86_64__
    - -DOS_LINUX
    - -I${CK_DIR}/src
    - -I${CK_DIR}/base
    - -I${CK_DIR}/base/base
    - -I${CK_DIR}/programs
Diagnostics:
  Suppress: '*'
Style:
  AngledHeaders: ['.*']
EOF
  echo "wrote ${CK_DIR}/.clangd"
}

[[ -d "${OB_DIR}" ]] && write_ob_clangd || echo "skip: ${OB_DIR} not present"
[[ -d "${CK_DIR}" ]] && write_ck_clangd || echo "skip: ${CK_DIR} not present"
